### ISSUE TITLE
Add build system

### ISSUE THREAD

**Issue by anirudhSK** [anirudhSK/needlstk#4]

**Comment by anirudhSK** [comment]
Apache Ant seems like the make equivalent for Java. Apache Maven seems like the automake/autoconf equivalent. ANTLRv4 doesn't seem to have ANT support (http://stackoverflow.com/questions/18949004/is-there-an-antlr4-ant-task), but seems to have Maven support (http://www.antlr.org/api/maven-plugin/latest/). Maybe we should use Maven, even though it might be too heavy weight for us. We can decide this later though.

**Comment by anirudhSK** [comment]
Ok, ditching this for now, because our heavy handed "javac *.java" is good enough. javac does some fairly sensible and intelligent automatic compilation to handle dependencies (http://docs.oracle.com/javase/7/docs/technotes/tools/windows/javac.html#searching), so this should suffice for now. Besides, it doesn't take too long to build.

**Comment by ngsrinivas** [comment]
Fair enough. I'm wondering about creating packages/organizing the classes by directory, since the number of .java files has grown quite a bit. Not the highest priority right now, but still.
